-- Хранилище аудита: станции, их сводки, прогнозы моделей и журнал выгрузок.
-- Типы подобраны так, чтобы миграция одинаково шла на PostgreSQL и на H2 в тестах.

create table station (
    wmo        varchar(8) primary key,
    city       varchar(64) not null,
    region     varchar(32) not null,
    latitude   double precision,
    longitude  double precision,
    -- Запрос к узлу Белгидромета, которым получены сводки станции.
    source_url varchar(512)
);

-- Одна строка — один срок наблюдения станции. Значения хранятся как их передал узел;
-- humidity рассчитана по температуре и точке росы.
create table observation (
    station_wmo      varchar(8) not null references station (wmo),
    report_time      timestamp with time zone not null,
    temperature      double precision,
    dew_point        double precision,
    humidity         double precision,
    pressure_sea     double precision,
    pressure_station double precision,
    wind_speed       double precision,
    wind_direction   double precision,
    visibility       double precision,
    cloud_cover      double precision,
    precipitation    double precision,
    min_temperature  double precision,
    max_temperature  double precision,
    -- Сколько из четырёх сравниваемых величин не прошли проверку правдоподобности.
    rejected_values  smallint not null default 0,
    source           varchar(32) not null,
    loaded_at        timestamp with time zone not null,
    primary key (station_wmo, report_time)
);

create index observation_report_time_idx on observation (report_time);

-- Прогноз модели на целевой час, выпущенный за horizon_days суток до него.
create table forecast (
    station_wmo    varchar(8) not null references station (wmo),
    model          varchar(32) not null,
    variable       varchar(16) not null,
    horizon_days   smallint not null,
    target_time    timestamp with time zone not null,
    issued_time    timestamp with time zone not null,
    forecast_value double precision not null,
    loaded_at      timestamp with time zone not null,
    primary key (station_wmo, model, variable, horizon_days, target_time)
);

create index forecast_target_time_idx on forecast (target_time);

create table ingest_run (
    id           bigint generated by default as identity primary key,
    job          varchar(32) not null,
    started_at   timestamp with time zone not null,
    finished_at  timestamp with time zone not null,
    status       varchar(16) not null,
    rows_written integer not null,
    message      varchar(1000)
);
